# -*- coding: utf-8 -*-
"""Crypto_project_problem2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PoTitpb7P7CBBoY8WwMIbJH-069wyfry

**Problem number 2**

Homomorphic properties
A notable feature of the Paillier cryptosystem is its homomorphic properties along with its non-deterministic encryption (see Electronic voting in Applications for usage). As the encryption function is additively homomorphic, the following identities can be described:

Homomorphic addition of plaintexts:
The product of two ciphertexts will decrypt to the sum of their corresponding plaintexts
*italicized text*
"""

c1 = 1431135290069325008583005767760440194352250669868642015637284664827863096526854295290213163196780672778228721128052234092877469782343204440819088345226674

c2 = 766502765098026355380112715536128541917607723218993231191798626637402444561652254317663096357141828249072007319292850196436742539757315839907222753619573

n = 61186929436230855420766379500946377903931541699202551225466267001310907409761

sum = (c1 * c2) % (n ** 2)

sum

"""sum corresponds to ENC(m1 + m2)

now for the second part

Paillier cryptosystem exploits the fact that certain discrete logarithms can be computed easily.


بعد تو قسمت بکگراند توضیح داده که با داشتن 

g^m


چجوری میشه خود 


m mod n 


رو حساب کرد
"""

c = 1857855433435253966261472405564630068207257435599367652422302291177346557860873816680098602083496236349568385254262863758166153798362744023058732538696778
r = 14935127747067141332266439078227426312235659727377265398012065621101840712218
n2 = 70700063534546514342061240350548864227722633715593560476868914510092441292783

g_topow_m = (c * pow(r,-n2,n2**2))%(n2 ** 2)

#طبق فرمول ویکیپدیا
import math 
m = math.floor((g_topow_m - 1) / n2)

m

"""m is plaintext message according to this problem"""